title: Nakamoto 101 (Breaking Down the Bitcoin Whitepaper)
remote_theme: pmarsceill/just-the-docs
footer_content: "<a href=\"https://github.com/chiselinc/nakamoto101/\">View on GitHub</a>"
color_scheme: bitcoin
